### ISSUE TITLE
逻辑组的锅

### ISSUE THREAD

**Issue by hzsydy** [hzsydy/XiangGuHuaJi#18]
- [x] testbench
- [x] testbench with network
- [x] test ai
- [x] test ai with network
- [x] params

**Comment by sugar10w** [comment]
testbench format:
```
### comments go after `#`
### Bidding phase
0    # price
4 4  # position

### Main phase
0 0 0          # diplomatic command
4 4 10  -1     # position+bomb_size, end with `-1`
4 4            # new capital
```

**Comment by sugar10w** [comment]
HuaJiCmd，HuaJiServer ，HuaJiClient 均产生 log,txt 文件。
可用 `python LogToTestbench.py -i log.txt -o t.txt` 转化为testbench。
